### ISSUE TITLE
Plugin does not work on SonarQube v7.3

### ISSUE THREAD

**Issue by wimnat** [mibexsoftware/sonar-bitbucket-plugin#93]
### Expected Behavior

I expect Sonar to start up.

### Actual Behavior

Sonar fails to start with the following exception:

```
java.lang.IllegalStateException: Fail to load plugin Bitbucket for Sonar [sonarbitbucket]
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
        at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:586)
        at org.sonar.server.platform.Platform.start(Platform.java:211)
        at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
        at org.sonar.server.platform.Platform.access$500(Platform.java:46)
        at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
        at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/batch/CheckProject
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
        at ch.mibex.bitbucket.sonar.SonarBBPlugin.define(SonarBBPlugin.scala:135)
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:72)
        ... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.batch.CheckProject
        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
        ... 24 common frames omitted
```

### Plug-in version, SonarQube version, CI system, build type

Plugin version: 1.2.3
Sonar version: 7.3 (build 15553)
OS: Amazon Linux

**Comment by rhaex** [comment]
+1

**Comment by dzmitry-rudnouski** [comment]
Caused by https://jira.sonarsource.com/browse/SONAR-10138.

**Comment by Ali-Shaikh** [comment]
Will it be fixed? what's the status on this?

**Comment by nicuamar** [comment]
+1

**Comment by rhaex** [comment]
When is this issue going to be addressed? Any updates?

**Comment by niyazabbasov** [comment]
Any updates?

**Comment by maxcherednik** [comment]
Guys, are you sure this plugin will work at all on 7.3? 
This plugin was originally a copy of the Github plugin, which was deprecated recently with the 7.3 version. Now they have built-in functionality for the github. But it can be used only within paid version of the sonarqube.

**Comment by iamthereplicant** [comment]
Any updates at this point?

**Comment by ph-One** [comment]
This plugin is holding us back from upgrading SonarQube. Does anyone have a fork/different plugin with the same functionality that can be used on SQ 7.3+?

**Comment by mrueegg** [comment]
Hi,

Please excuse my late response and the delay of the update. I now have a version compatible with SQ 7.4 ready. I'll do a few more tests and will publish it in the next couple of days.

I'll keep you up-to-date.

Best regards,
Michael

**Comment by andrew-makarenko** [comment]
Thank you for your hard work! That's really amazing!

**Comment by Cezarion** [comment]
yep, thank you very much !

**Comment by lukaszun** [comment]
Any update on this issue?

**Comment by ph-One** [comment]
I would love for GitHub to have hit counters for issues :smirk:

**Comment by mrueegg** [comment]
Hi all,

I've just committed a new version which is compatible with latest SQ versions (>= 6.5). Please check it out and let me know if you experience any issues.

Thanks,
Michael

**Comment by mcollovati** [comment]
Can confirm that the plugin works with SQ 7.5. 
Thank you very much

**Comment by ph-One** [comment]
Confirmed that the plugin works on 7.6 Community Edition. :beers:

**Comment by mrueegg** [comment]
Perfect, thanks for your feedback!

**Comment by mjlabe** [comment]
Is this fixed in the Atlassian App store? I'm getting this error with SonarQube 7.7 and the version I installed from the Atlassian store.

**Comment by titusprasetyo** [comment]
> Confirmed that the plugin (commit [ae762ea](https://github.com/mibexsoftware/sonar-bitbucket-plugin/commit/ae762eaaa60b005a9831afbeab7724dfa812bde7)) works on SQ 7.6 Community Edition. 🍻

I still got error on SQ 7.6


`2019.12.06 04:52:08 INFO  web[][o.s.p.ProcessEntryPoint] Starting web
2019.12.06 04:52:08 INFO  web[][o.a.t.u.n.NioSelectorPool] Using a shared selector for servlet write/read
2019.12.06 04:52:09 INFO  web[][o.e.p.PluginsService] no modules loaded
2019.12.06 04:52:09 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
2019.12.06 04:52:09 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
2019.12.06 04:52:09 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2019.12.06 04:52:11 INFO  web[][o.s.s.e.EsClientProvider] Connected to local Elasticsearch: [127.0.0.1:9001]
2019.12.06 04:52:11 INFO  web[][o.s.s.p.LogServerVersion] SonarQube Server / 7.6.0.21501 / d56689a5eb122c06cf87375828085609f5a68323
2019.12.06 04:52:11 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:postgresql://10.0.0.152/sonarqube?currentSchema=sonarqube
2019.12.06 04:52:12 INFO  web[][o.s.s.p.ServerFileSystemImpl] SonarQube home: /home/ubuntu/sonarqube-7.6
2019.12.06 04:52:12 INFO  web[][o.s.s.u.SystemPasscodeImpl] System authentication by passcode is disabled
2019.12.06 04:52:12 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin Bitbucket for Sonar / 1.2.3 / 0
2019.12.06 04:52:12 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin Git / 1.7.0.1491 / 1d54e49a5f952dfb4ccded090f8043a2a62d0372
2019.12.06 04:52:12 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin JaCoCo / 1.0.1.143 / 65c55e41e32c114704fd597ccea91fc55becb4ec
2019.12.06 04:52:12 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin LDAP / 2.2.0.608 / 79dc3fa4393a29667673c70182f3016288b548b7
2019.12.06 04:52:12 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarC# / 7.10.0.7896 / 4e51d150065288432fd1411d29d5aebf2ab7f133
2019.12.06 04:52:12 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarCSS / 1.0.3.724 / 3ad5232345519caed38a24c70fb77e91757833bf
2019.12.06 04:52:12 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarFlex / 2.4.0.1222 / 68d9cb3b7daccbc4869c4f2b89d09218d26a0829
2019.12.06 04:52:12 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarGo / 1.1.0.1612 / 1809c7be6d88396c0a1b8d597b1e9e0ed8d29730
2019.12.06 04:52:12 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarHTML / 3.1.0.1615 / 4181edb5eff5605bec82dc0aa15ecd70eaa5857f
2019.12.06 04:52:12 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarJS / 5.0.0.6962 / ac2fe7567f3dfeb3295e2e710afd8c06b7760e9d
2019.12.06 04:52:12 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarJava / 5.10.1.16922 / 448c4b8fce8d8ac53a9a7a7265d4de1c1ac87a4e
2019.12.06 04:52:12 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarKotlin / 1.4.0.155 / f71ae433edd0c1f1dbab3fed4d755ef17aef8573
2019.12.06 04:52:12 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarPHP / 2.16.0.4355 / 80c76cb14e9eae6bd982fa6ac8c39b2de1f89b6f
2019.12.06 04:52:12 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarPython / 1.11.0.2473 / 3ec86bb66699ff9ccf2c00c84f360210eb3ffd8d
2019.12.06 04:52:12 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarRuby / 1.4.0.155 / f71ae433edd0c1f1dbab3fed4d755ef17aef8573
2019.12.06 04:52:12 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarScala / 1.4.0.155 / f71ae433edd0c1f1dbab3fed4d755ef17aef8573
2019.12.06 04:52:12 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarTS / 1.9.0.3766 / 4a4080b78001a78d758d1d0fa0190fb9496b6f57
2019.12.06 04:52:12 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarVB / 7.10.0.7896 / 4e51d150065288432fd1411d29d5aebf2ab7f133
2019.12.06 04:52:12 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarXML / 2.0.1.2020 / c5b84004face582d56f110e24c29bf9c6a679e69
2019.12.06 04:52:12 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin Svn / 1.9.0.1295 / 942e075773975354e32691a60bfd968065703e04
2019.12.06 04:52:13 INFO  web[][o.s.s.p.d.m.c.PostgresCharsetHandler] Verify that database charset supports UTF8
2019.12.06 04:52:13 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.ws.WebServiceFilter@67ab5498 [pattern=UrlPattern{inclusions=[/api/system/migrate_db.*, ...], exclusions=[/api/properties*, ...]}]
2019.12.06 04:52:13 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2019.12.06 04:52:14 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Fail to load plugin Bitbucket for Sonar [sonarbitbucket]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:573)
	at org.sonar.server.platform.Platform.start(Platform.java:211)
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
	at org.sonar.server.platform.Platform.access$500(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/batch/CheckProject
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	at ch.mibex.bitbucket.sonar.SonarBBPlugin.define(SonarBBPlugin.scala:135)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:72)
	... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.batch.CheckProject
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 24 common frames omitted
2019.12.06 04:52:14 INFO  web[][o.s.p.StopWatcher] Stopping process`
